### ISSUE TITLE
Create models and associations

### ISSUE THREAD

**Issue by ebouchut** [ebouchut/rails-app-template-bugtracker#2]
## Bug
- [x] **Name**
- [x] **Description**
- [x]  **Status**: New, Opened, Done, Closed
- [x] **Priority**: Low, Normal, High
- [ ] **Assignee**: Assigned to a single User
- [ ] **Milestone**: Intended to be fixed in a given Milestone
- [x] **Start Date**
- [x] **End Date**
## Milestone
- [ ] **Name**
- [ ] **Version**
- [ ] **Due Date**
## User
- [ ] **Name**
- [ ] **E-mail**
## Project
- [ ] **Name**
- [ ] **Milestones**
- [ ] **Users**
